name: Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  tests:
    runs-on: ubuntu-latest
    env:
      TEST_DATABASE_URL="sqlite://:memory: pytest"
      CONFIG_MODE: testing
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Copying configurations
      #   run: cp .env_samples .env

      - name: Tests
        run: pytest
